# Use an official Python runtime as a parent image
FROM python:3.11

# Install netcat
RUN apt-get update && apt-get install -y netcat-openbsd

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV CELERY_BROKER_URL=redis://redis:6379/0

# Create a user for celery
RUN adduser --disabled-password celeryuser

# Switch to the new user
USER celeryuser

# Run Django's development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
