# Generated by Django 5.1.1 on 2024-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
