# Generated by Django 5.1.1 on 2024-12-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
