# Generated by Django 5.0.7 on 2024-08-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('bye_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quarterback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('bye_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RunningBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('bye_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TightEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('bye_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WideReciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('bye_week', models.CharField(max_length=20)),
            ],
        ),
    ]
