# Generated by Django 5.0.7 on 2024-08-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('bye_week', models.CharField(max_length=20)),
            ],
        ),
    ]
