# Generated by Django 5.0.7 on 2024-08-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_defense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='team',
        ),
    ]
