# Generated by Django 5.0.7 on 2024-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_remove_defense_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='adp',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='kicker',
            name='adp',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='adp',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='adp',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='runningback',
            name='adp',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='tightend',
            name='adp',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='widereciever',
            name='adp',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
