# Generated by Django 5.0.7 on 2024-08-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_defense_adp_kicker_adp_player_adp_quarterback_adp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='info',
            field=models.URLField(default='N/A'),
        ),
        migrations.AddField(
            model_name='kicker',
            name='info',
            field=models.URLField(default='N/A'),
        ),
        migrations.AddField(
            model_name='player',
            name='info',
            field=models.URLField(default='N/A'),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='info',
            field=models.URLField(default='N/A'),
        ),
        migrations.AddField(
            model_name='runningback',
            name='info',
            field=models.URLField(default='N/A'),
        ),
        migrations.AddField(
            model_name='tightend',
            name='info',
            field=models.URLField(default='N/A'),
        ),
        migrations.AddField(
            model_name='widereciever',
            name='info',
            field=models.URLField(default='N/A'),
        ),
    ]
